spring:
  datasource:
    url: jdbc:h2:file:./src/main/resources/static/demodb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
server:
  ssl:
    key-store: classpath:demo.jks
    key-store-type: pkcs12
    key-store-password: password
    key-password: password
    key-alias: demo
    server.port: 8443